// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcmsuswvdmdhourtmuvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjbXN1c3d2ZG1kaG91cnRtdXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2OTU3MjcsImV4cCI6MjA2MDI3MTcyN30.9okuZS8ttSXukCgU85d8bI2cnQ5bKuzcJDJlgqg-I-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);